### ISSUE TITLE
Settings location

### ISSUE THREAD

**Issue by sebinemeth** [ekho/docker-utorrent#15]
Hi,
Sorry for the ignorance but I am unable to change settings.
According to the description I mounted an external dir to `/utorrent/settings`, but this dir does not contain any `.conf` files. The only conf file I found inside the container was `/utorrent/utserver.conf` but that can not be modified from outside. Or can it?
Thanks
Sebi

docker-compose.yml:
```
version: "2"

services:
  utorrent:
    container_name: utorrent
    restart: unless-stopped
    image: ekho/utorrent:latest
    volumes:
      - ./data:/data
      - ./config:/utorrent/settings
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
```
